language: python
python:
- "2.7"
- "3.6"
- "3.8"
script:
- coverage run ./setup.py test
install:
- pip install http://twhiteman.netfirms.com/pyDES/pyDes-2.0.1.zip
- pip install coveralls
after_success:
- coveralls


